# Экономим память как последние нищие
shared_buffers = 128MB
effective_cache_size = 256MB
work_mem = 16MB
maintenance_work_mem = 32MB
max_connections = 50
# Логируем медленно, чтобы диск не ебать
log_min_duration_statement = 1000
listen_addresses = '*'