database:
  host: 127.0.0.1
  name: trade_db
  password: qaZXsw21Aa!
  port: '5432'
  schema: tink
  user: khanin
settings:
  config_reload_interval_seconds: 60
  default_history_depth_days: 365
  default_timeframe: 1d
  log_file: logs/app.log
  log_level: ${LOG_LEVEL:-INFO}
  timezone: "Europe/Moscow"
tinkoff:
  token: ${TINKOFF_TOKEN}
telegram:
  enabled: true
  token: ${TELEGRAM_BOT_TOKEN}  # <-- вынеси в .env!
  chat_id: ${TELEGRAM_CHAT_ID}  # <-- вынеси в .env!
  notify_on: ["BUY", "SELL"]    # на какие сигналы реагировать
  disable_notification: false   # не издавать звук (для ночных сигналов)
